### ISSUE TITLE
[MariaThelast]W6-api-sentiment

### ISSUE THREAD

**Issue by mariadelascotrina** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#1]
https://github.com/mariadelascotrina/Sentimentalmente.git

**Comment by AnaAGG** [comment]
# Proyecto Flask

Hola hola María 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Buen trabajo María! Tienes un readme muy bien explicado, te dejo por aquí unos *tips* por si te aportan valor en el futuro:

- Podrías incluir el link de la página de donde te hayas descargado los datos de las frases

- En este proyecto la estructura del repo era bastante compleja, por lo que estaría bien incluir un apartado donde contaramos brevemente que carpetas tenemos y que nos podemos encontrar en cada carpeta

- Cuando enseñas los *endpoints* que tienes, podemos incluir un ejemplo de lo que nos devuelve

- Sobre las librerías, super bien que las incluyeras con sus links. Solo por ponerme un poco quisquillosa, te sale así:

  pandas https://pandas.pydata.org/docs/

  Para evitar que nos salga así de "feote" tenemos que hacerlo así: 

  ```
  [pandas](https://pandas.pydata.org/docs/) # todo seguidito y sin dejar espacios. 
  ```
Por el resto, todo perfectito María 💪!

## Estructura del repo

Bueno María, solo puedo darte la enhorabuena por la organización de tu proyecto. Solo como detalle: 

- Tienes un jupyter con el código de tu BBDD. En vez de tenerlo dentro de los jupyters, nos podemos crear una carpeta que sea `sql_scripts` por ejemplo donde guardemos este tipo de ficheros

## Sintaxis de código


- Tienes algunas funciones en los jupyeters, y algunas sin documentar tanto en el jupyter como en el `.py`. 

  Recuerda: 

  ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
Por el resto esta todo perfectito María, como siguentes retos: 

- Añadir más endpoints de post como de eliminar o actualizar una entrada de tu API
- Añadir más enpoints con el análisis de sentimientos donde comparemos entre personajes o saquemos gráficas.

## TODOs

Poquito tengo que decirte aquí: 

- Añadir los *docstrings* en las funciones
- Tal vez crearnos una nueva carpeta con los código de sql
- Cambiar los imports en el readme

Venga María que ya estamos en la recta final 🔥🔥🔥! 

![image](https://user-images.githubusercontent.com/75084991/145029177-5b1d98e7-4d95-4f1b-8819-74a2a011f3cd.png)
