### ISSUE TITLE
[W6-api-sentiment-project] Juan Perez de Ayala

### ISSUE THREAD

**Issue by Juanpda** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#10]
https://github.com/Juanpda/W6-api-sentiment-project.git

**Comment by AnaAGG** [comment]
Hola Juan

He visto por encima que has hecho un buen trabajo. Sin embargo,, sabemos que un proyecto sin readme es un proyecto NO entregado. No lo voy a considerar como tal, pero en este caso no recibiras feedback de tu trabajo

**Comment by Juanpda** [comment]
Justo acabo de actualizar el README.md que se me había olvidado. Entiendo que sin el README es imposible dar feedback porque conllevaría mucho más tiempo. Le he echado mil horas a este proyecto y por eso he tardado tanto en tenerlo actualizado. Muchas gracias y perdona por olvidarme! 

Pd: no lo he actualizado para que me des feedback sino para tenerlo completo, que sé que estáis super liadas. Gracias Ana!
