### ISSUE TITLE
[W6-api-sentiment-project] Blanca Vispo

### ISSUE THREAD

**Issue by bvispo** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#11]
https://github.com/bvispo/API-project

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Blanca 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Muy buen trabajo con el readme Blanca, enhorabuena! Solo un par de detallines: 

- Cuando haces los import lo tienes así:

  ```python
  import requests
  import pandas as pd
  import numpy as np

  # no hace falta que incluyamos el import, por lo tanto, nos quedaría así: 
  requests
  pandas 
  numpy 
  ```

- Por otro lado, este proyecto tiene una estructura algo más compleja que otras veces, por lo que sería ideal que incluyeramos un apartado donde explicaramos brevemente la estructura del repo. Qué carpetas tenemos, que ficheros tenemos en ellas, etc. 

Por el resto, perfectísimo 💪! 

## Estructura del repo

Congrats Blanca! Super bien organizado, solo un detalle: 

- En la carpeta de `notebooks` tienes dos jupyters, para que nos quede redondita la organización lo que podemos hacer es numerar los jupyters para que sepamos cual es el orden de trabajo. 

- No se te ha pasado ningún archivo rarinchi fuera del `.gitignore` Blanca 👏🏽 yujuuuu

Increíble la organización 🔥! 

## Sintaxis de código

- Tienes el nombre de las funciones en español pero el resto de las cosas en ingles. Unifícalo! Incluso tienes algunas funciones sin *docstring* o en español. 

- En las funciones que tienes *docstrings* , super bien que los tengas pero como detalle, lo ideal sería que lo tuvieras como viene definido por convenio. 

   Recuerda, ¿qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Se te han pasado la funciones  `seasons` y `hacestring` dentro del jupyter de limpieza. Recuerda llevarla al `.py`

Por el resto todo muy bien Blanca, tienes varios endpoints, tanto de GET como de POST. Buen proyecto! 

## TODOs

- Las librerías y la estructura del repo en el readme. 

- Los *docstrings* en las funciones. 

- Mover algunas funciones que tienes en los jupuyters al `.py`. 
  
- Como reto para el futuro: crearnos algún endpoint más que por ejemplo nos permita actualizar algún dato de la base de datos. 

Pocos comentarios te pude hacer en el proyecto, tienes un gran trabajo. Enhorabuena 🙌🏽!

Venga venga que ya no nos queda nadaaaa 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/144834843-89c698b2-7b31-44b6-8a36-d6a28e025476.png)
