### ISSUE TITLE
[W6-api-sentiment-project] María Pérez de Ayala

### ISSUE THREAD

**Issue by mariaperezdeayalas** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#12]

**Comment by mariaperezdeayalas** [comment]
https://github.com/mariaperezdeayalas/API-Sentiment-Project-

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola María 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Bueno María, la verdad es que tienes un readme muy bueno, no tengo nada que decirte. Solo por ponerme un poco quisquillosa te diría que:

- Me falta un poco de mejor manejo del *markdown* 
- Hubiera estado bien que incluyeras algún ejemplo de algunos *endpoints* tuyos mostrando además que es lo que devuelve. 

Enhorabuena por el readme 👏🏽!

## Estructura del repo
Tienes tus ficheros super bien modularizados, buen trabajo. Solo como detallines que he visto que nos pueden ayudar a mejorar: 

- Se nos han pasado algunos archivos temporales fuera del `gitignore` como por ejemplo: 
  - Los *checkpoints* del jupyter. 
  - EL `__pycache__` dentro de la carpeta de configuración y src
  - El .`DS_Store`

  Recuerda que estos archivos no aportan valor a nuestro proyecto y que por lo tanto deben ir al `.gitignore`. 

- Tienes por ahí una imagen suelta. Lo que podemos hacer es crearnos una carpeta donde vayamos almacenando las imágenes, aunque sea solo una. 
- En el caso de la carpeta de `notebooks` lo que podemos hacer es numerar los jupyters para saber cual es el orden de trabajo. 

  
Por el resto todo perfecto 🙌🏽! 

## Sintaxis de código

Vamos con la parte de código! 

- Solo como detalle, en la parte de limpieza tienes estas lineas de código: 

  ```python
  df['author'] = df['author'].str.lower()
  df['author'] = df['author'].str.capitalize()

  # en realidad no te hace falta hacer las dos cosas. Puedes hacer el `capitalize` directamente y se te cambiará independiete de que este todo en mayúsculas o minúsculas. 
  ```
- Respecto a esto: 

  ```python
  df["episode_number"] = df["episode_number"].astype(dtype="int64")
  # lo haces para dos columnas diferentes. Aquí se puede medio llevar porque son dos columnas,pero imaginate que tuvieras 50! Locura. Lo podemos hacer en una única línea . 

  df[["episode_number", "season"]] = df[["episode_number", "season"]].astype(dtype="int64")
  ```
- Respecto a los *docstrings* genial que lo hayas incluido! Solo como detalle, recuerda, para tener una buena documentación de nuestras funciones tenemos que incluir: 

    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función MUY SINTETIZADO, EN UNA ÚNICA LÍNEA
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Ya somos programadores de nivel y una lista de números lo debemos hacer con un range y no a mano 😂

  ```python
  seasons = [1,2,3,4,5,6,7,8,9,10] #🚨
  seasons = list(range(1,11))
  ```
- Por el resto, todo perfectito María. Solo como reto para el futuro: 
  - Incluir algún endpoint más de POST:
    - Algunos de eliminar
    - Alguno de actualizar algo que este mal. 

## TODOs
Buen trabajo María, ahora solo queda repasar el readme y algunas partes del código. Te dejo aquí un pequeño recap:

- Los archivos temporales al `.gitignore`
- Los *docstrings* 
- Algún ejemplo de tus endpoints en el readme. 

Venga María, que ya no queda nadaaaa 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/144721320-3d02d327-8301-4fc4-82f0-021608e7a0b7.png)
