### ISSUE TITLE
[API Sentiment Project] Andrés Uzcátegui

### ISSUE THREAD

**Issue by baccandres** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#13]
https://github.com/baccandres/StarWarsSQLAPISNL

No me funciona el markdown para el landing de la API.

**Comment by AnaAGG** [comment]
# Proyecto Flask Andrés U. 

Hola hola Andrés 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

En general el readme esta bastante completo. Peeero ya sabes que siempre tenemos algún detallin que comentar. Te los dejo por aquí: 

- Podrías poner el link a la página de kaggle de donde te has descargado los datos de la BBDD. 

- Cuentas los *endpoints* que tienes lo cual esta perfecto. Pero me ha faltado que pongas algo más de documetación de tu API. Por ejemplo, poner algún ejemplo de tus *endpoints* 

- Faltan las librerías que has usado en este proyecto y recuerda de poner los links a la documentación oficial. 



## Estructura del repo

El repo esta suuper bien modularizado Andrés, buen trabajo 👏🏽! Aún así te dejo por aquí unos detalles por si te aportan valor: 

- Se nos han quedado fuera del `.gitignore` algunos archivos temporales como el `.DS_Store` o el `__pycache__`(dentro de la carpeta de configuarción) , los `checkpoints`, recuerda todos estos ficheros que no nos aportan valor deben ir al `.gitignore`

- En la carpeta de `data` tienes otra carpeta con imagenes. Dado que esto no son datos, lo que yo haría sería crear una carpeta en la raíz del repo que se llame `images` donde las vayas guardando todas. 
  
- El `.env` con el token, recuerda que tiene que ir al `gitignore` para que la gente no vea tu token. 

- Dentro de la carpeta `data` también tienes unos *scripts*  de sql. Mi recomendación es que te crees una nueva carpeta que se llame por ejemplo `SQL_scripts` donde guardemos todos estos ficheros. 

- Super bien la carpeta `notebooks`, solo por ponerme quisquillosa. Si numeras los jupyters para saber cual es el orden de trabajo ya sería perfecto. 


- Tienes algunas cosas en inglés y otras en español. Intenta homogeneizarlo todo al mismo idioma. 

## Sintaxis de código

- Faltan los *docstrings* en las funciones Andréssssss 😔! 

    ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función MUY SINTETIZADO, EN UNA ÚNICA LÍNEA
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Super bien que tuvieras un jupyter donde haces las pruebas de tu endpoints, eso si, tienes unos *prints* **infinitos** que me hacen llorar. 
- Poco más tengoq ue decirte Andrés. Lo tienes todo. Solo como detalle o retos para el futuro:
  - Hacer algun endpoint de POST más, por ejemplo para eliminar frases o actualizar alguna
  - Temabién podríamos hacer un endpoint que nos devuelva una figura donde comparemos por ejemplo la polaridad entre episodios o entre personajes. 


## TODOs

- La API más documentada
- Las librerías que has usado con sus links a la documentación oficial.
- Reorganizar un poco el repo
- Los *docstrings* de las funciones

Bueno Andrés, poco más que decirte, buen trabajoooo. 

Venga venga que ya estamos en la recta finalllll 🔥💪💪🔥!! 


![image](https://user-images.githubusercontent.com/75084991/144718894-23d516ce-6ff1-4aee-b787-763cbdc1ab84.png)
