### ISSUE TITLE
[W6-api-sentiment-project] Ana Walsh

### ISSUE THREAD

**Issue by AnaWalsh** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#14]
https://github.com/AnaWalsh/W6-api-sentiment-project

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Ana 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README
Anaaaa que buen readme hiciste!!! Solo unos detalles: 

- Entiendo que te bajas el csv de kaggle. Lo que podemos hacer es poner el link a la página de kaggle de donde te lo descargaste. 
  
- Me han faltado las librerías que has usado en este repo con sus links. 

- Este proyecto tenía una estructura algo más compleja, con unas cuantas carpetas y ficheros de distintos tipos. Podríamos haber incluido una parte explicando la estructura del repo, que carpetas nos podemos encontrar y que hay en cada una, de una forma muy esquemática. 

Por el resto todo perfectito Ana 👏🏽! 

## Estructura del repo

En general esta todo muy bien, muy modularizado y fácil de seguir. Vamos con algunas cosinas que vi: 

- En la carpeta `notebooks` puedes numerar los ficheros para saber en que orden van
  
- Cuidado que se nos han pasado algunos ficheros temporales como el `__pycache__` fuera del `.gitignore` en las carpetas de `src` y `configuration`

- En la carpeta `data` tienes los `csv` lo cual esta perfecto. He visto que también tienes el esquema de SQL y el código que genera la BBDD. Lo ideal, es que nos crearamos una carpeta por ejemplo `sql_scripts` y guardemos todo eso. En este sentido, tienes un fichero en la raíz del repo que se llama `create_table` que también podría ir a esta carpeta. 

Por el resto todo perfecto 🙌🏽. 

## Sintaxis de código

- En el jupyter de limpieza tienes esta función: 

  ```python
  def mayus(string):
    return string.capitalize()
  ```
  Dos cosas: 
  - Si creamos una función, nos la llevamos a un `.py` y la documentamos. 
  - Cuando tenemos un método que nos hace algo específico no tiene mucho sentido crearnos una función. Este es el caso de `capitalize`. 

  ¿Qué podríamos hacer? 

  ```python
   friends.author = friends.author.str.capitalize()
  ```
- Recuerda, los `import` siempre al inicio del jupyter, para que cuando abramos tu código sepamos con que librerías vamos a trabajar. 

- En el `.py` de `main_tools` faltan los *docstrings* en las funciones.

Poco más que decirte Ana, al final en este repo casi todas las funciones que hemos usado vienen de clase y un poco retocadas para nuestro propósito. 

## TODOs

Enhorabuena Ana, buen trabajo. Te has creado algunos *endpoints* de GET y un par de POST, incluso has hecho uno que nos elimina cositas 👏🏽. Como siempre, te dejo por aquí un resumen de lo que te comento:


- Los *docstrings*  en las funciones
- Las librerías que has usado en el repo en el readme. 

Venga Ana, que ya estamos casi al finalll 🔥💪🔥🔥

![image](https://user-images.githubusercontent.com/75084991/144743676-f682ef31-4e67-40da-8ad5-7795ae36c838.png)
