### ISSUE TITLE
[W6-api-sentiment-project]Daniela Arias

### ISSUE THREAD

**Issue by daniela-arias** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#15]
https://github.com/daniela-arias/API_Flask

**Comment by AnaAGG** [comment]
Hola Daniela, 

He visto tu repo y no tienes readme 😱! Como ya dijimos un proyecto sin readme se considera como un proyecto no entregado, y tenemos que recordar que para graduarse hay que tener los proyectos entregados. 

En esta situación te recomendaría que lo hicieras. 

En cualquier caso, dado que has entregado un proyecto sin readme, no te devolveremos nigún feedback de tu proyecto.
