### ISSUE TITLE
[W6-api-sentiment-project] Jose Díaz

### ISSUE THREAD

**Issue by TheIronhidex** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#16]
https://github.com/TheIronhidex/W6-api-sentiment-project

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola José 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

El readme tiene una buena estructura con un buen *storytelling*, buen trabajo por esta parte José. Vamos allá con algunos detalles: 

- Cuando pones los endpoints que tienes, lo ideal es que incluyas algunos ejemplos de lo que nos devuelve cada uno de los enpoints.

- Pones las librerías que has usado, recuerda que poner los links a la documentación oficial aporta mucho valor. 

- Cuentas la estructura del proyecto, super bien! En este caso, este repositorio también tiene una estructura bastante compleja, estaría bien si incluyeramos un apartado donde contáramos que carpetas teníamos y que nos podíamos encontrar en ellas.

## Estructura del repo
En general esta bastante bien, aún así te dejo por aquí algunos *tips* por si te aportan valor:

- Sigues añadiendo los ficheros con un *drag and drop* ? 🤔

- Tienes los jupyters numerados 👏🏽. Ahora solo nos falta meterlos en una carpeta que se llame por ejemplo `notebooks` para que quede redondito. 

- Tienes una imagen por ahí suelta. Lo ideal, crearnos una carpeta de imagenes y guardarla allí, aunque sea solo una.

- Dentro de la carpeta `data` tienes una carpeta que se llama `sql`, lo ideal sacarla de ahí y ponerla en la raíz principal del proyecto. 

- No tienes `gitignore`!!!! Como "escondes" los ficheros que no debemos mostrar 🤔

- Dentro de la carpeta `src` tienes un fichero sin extensión y vacío. Eliminalo! 

## Sintaxis de código
- Tienes funciones en los jupyters, recuerda llevartelas al `.py`. 
- Documenta las funciones!

  ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Respecto a la API, queda muchísimo trabajo por hacer José. Lo importante es que de esta experiencia hayamos sacado un aprendizaje, y es que si tenemos que cumplir unos objetivos, no nos podemos perder en tareas que no eran obligatorias para el proyecto. 

## TODOs

- Documentar las funciones

- El `.gitignore`

- Seguimos subiendo los ficheros con *drag and drop*? 

Venga que ya no queda nadaaaa 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/145151652-8e2fb80f-53f4-4a73-a1a3-e812088f4439.png)
