### ISSUE TITLE
W6-api-sentiment-project - Silvia Rico

### ISSUE THREAD

**Issue by silviarico** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#17]
https://github.com/silviarico/W6-api-sentiment-project.git

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Silvia 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Ais Siliviiiiiiii que el readme de tu proyecto es el readme que os presentamos nosotras!!! 

- ¿Qué es lo que teniamos que tener en este readme? 

  - Objetivo del proyecto

  - Herramientas que hemos usado

  - Ejemplos de tus endpoints

  - Contar de donde habías sacados los datos y que es lo que nos contaba

  - Poner las librerías que hemos usado y los links a la documentación

  - Incluir un apartado donde contemos la estructura del repo

## Estructura del repo

En general la estructura esta super bien, pero te dejo un par de detallines que vi que pueden hacer que quede perfecto: 

- Se nos ha colado la carpeta de los *checkpoints* de jupyters. Recuerda, aquellos archivos temporales que se nos generan, así como ficheros que no queremos que se vean deben ir al `.gitignore`.

- Lo mismo pasa con el `__pycache__` que tienes dentro de las carpetas de `config` y `tools`. Al `.gitignore`. 

- Ya como detalles por ponerme un poco pijolis: 
  - Tienes los jupyters "sueltos" por el repo. Lo que podemos hacer es crearnos una carpeta que se llame `notebooks` donde almacenemos los jupyters. Si además los numeramos para saber cual es el orden de trabajo, quedaría super 🔝. 
  - Lo mismo te diría para las imagenes, aunque solo haya una. 

Por el resto, todo esta perfecto Silvia! Buen trabajoooo

## Sintaxis de código

Vamos con el código! 

- En el jupyter de insertar los datos a SQL, tienes las funciones en el propio jupyter. Nos podríamos haber creado un nuevo fichero (`.py`, nos podemos crear todos lo que queremos) donde guardemos todas esas funciones. 

- Me ha faltado la documentación de las funciones del `sql_tools`. A modo de recordatorio: 

    ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- En el jupyter de insertar los datos, tienes algunos *imports* repartidos por el jupyter. Lo ideal, tener todos los imports al inicio del jupyter para que el lector saber que tiene que importar. 

- Suuper bien que nos hayas incluido un jupyter con ejemplos de como funciona tu API 👏🏽🔝. 

- He visto que te ha dado algún problema el `nltk` y el `spacy`. Lo conseguiste solucionar? Si no es así dime y lo vemos juntas 😉

- La verdad es que el resto esta super bien. A modo de detalle, que me falto: 
  - Algún enpoint de post más
  - El análisis de sentimientos. 

## TODOs

- Documetación de las funciones
- Pasar las funciones que tenemos en el jupyter a un `.py`
- Incluir algún endpoint de POST como por ejemplo uno de actualizar e incluso de eliminar. Y si ya incluimos el del análisis de sentimientos, lo petamos! 

Aún con todo super buen trabajo Silvia! Has cumplido con todos los objetivos del proyecto, meter tus datos a SQL, crearte una API... Enohorabuena!!!

Vamos vamos vamos que ya estamos en la recta final 🔥💪💪! 

![image](https://user-images.githubusercontent.com/75084991/144707251-02309cea-64fd-4327-b718-2b3f11d0788d.png)
