### ISSUE TITLE
[W6-api-sentiment-project]Carlos_de_León

### ISSUE THREAD

**Issue by Carlosleono** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#18]
https://github.com/Carlosleono/API-creation-and-sentiment-analysis

**Comment by AnaAGG** [comment]
# Proyecto Flask

Hola hola Carlos 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Bueno Carlos, el readme parece que se te ha quedado a medias 😔. Lo que tienes escrito esta perfectisimo, sin embargo me han faltado algunas cosinas. Te dejo por aquí unos *tips* por si te aportan valor:

- Parece que ibas a describir como hacer el Sentiment Analysis, lo ideal es que lo incluyas si. 

- Este proyecto tiene un estructura bastante compleja, con muchas carpetas y ficheros dentro de las carpetas. Podríamos añadir un apartado en el readme donde exliquemos brevemente la estructura. 

- En cuanto a los endpoints. Pones los que tienes y como llamarlos, lo cual está perfecto. Lo que podríamos añadir es un ejemplo de cómo llamarlo y que nos devuelve

- También podemos añadir un esquemita muy breve de cual es el workflow de trabajo de este proyecto. 

Aún así, bien hecho Carlos. 

## Estructura del repo

Tienes tu repo muy bien modularizado, enhorabuena. Buena organización. Peero, siempre tenemos algun detallin que comentar, te los dejo por aquí: 

- Se nos han quedado los *checkpoints* fuera del `.gitignore`. 

- Dentro de la carpeta `src` tienes el `__pycache__` que debería ir también en el `gitignore` ya que son ficheros o carpetas que no le aportan valor a nuestro proyecto. 

- Tienes la base de datos incluida en el proyecto, suuuper bien. Lo que podriamos haber hecho tambien es crearnos una carpeta que se llame por ejemplo `sql_scripts` donde alamacenemos el código que crea la BBDD el esquema y todo lo derivado de nuestro trabajo en SQL. 

- Tienes algunas cosas en ingles y otras en español. Intenta homogeneizarlo. 


## Sintaxis de código

- Vamos con la función `nombres`, donde tienes un montón de `if` seguiditos 😔. Respecto a esto dos cosas:
  - Solo podremos muchos `if` seguidos si una condición no depende de la anterior. Que en este caso no es el caso, por lo tanto habría que usar `if` y `elif`. 
  - Cuando vemos que tenemos tantas condiciones seguiditas es el momento de usar un diccionario! 

    ¿Cómo lo podríamos hacer? 

    ```python
    def nombres(x):
      diccionario = {
        'TONY STARK' : re.match('.*TONY.*', x), 
        'STEVE ROGERS': re.match('.*STEVE.*', row), 
        ... # y así para todos los que quieras}
      for ke, value in diccionario.items():
        if value:
          return key
        else: 
          return "No info"

    marvel['character'] = marvel['character'].apply(sql.nombres)
    ```
- Los *docstrings*  de las funciones faltan. Y lo más importante, como muchas de las funciones vienen derivadas del código que os explico Ras en clase los *docstrings* no están completos. Recuerda, para tener una buena documentación de nuestras funciones tenemos que incluir: 

    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función MUY SINTETIZADO, EN UNA ÚNICA LÍNEA
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Suuper bien que tengas un jupyter donde haces pruebas de los endpoints y podamos ver lo que te devuelven 👏🏽!

- En este mismo jupyter también tienes el análisis de sentimientos:
  - Las funciones que tienes llevatelas a un `.py`. Recuerda que podemos tener tantos `.py` como queramos. Lo ideal, es que cada uno de ellos contenga funciones que "hacen cosas" específicas, por ejemplo limpiar dataframe, otro con las funciones de sql, otro con las del análisis de sentimientos, etc. 
  - Tienes imports a lo largo del jupyter. Recuerda, todos al incio para que cuando abramos el jupyter sepamos con que librerías vamos a trabajar. 
- En cuanto a los *endpoints* super bine, tienes un montón tanto de GET como de POST. Solo como reto para el futuro: 
  - Crear algún endpoint para eliminar alguna frase o personaje
  - Crear un endpoint para actualizar alguna entrada que este mal. 

## TODOs
Bueno Carlos te dejo por aquí un *recap* de lo que te he comentado a lo largo de la corrección. 

- Los *docsrtings* de las funciones
- Atomizar la funcion de `nombres`
- Los archivos temporales al `.gitignore`
- Terminar el readme

Aún con todo, hiciste un gran trabajo, como siempre 😉. Seguimos que ya no nos queda nadaaaaa 🔥💪💪🔥

![image](https://user-images.githubusercontent.com/75084991/144720160-fdbb66d5-de4a-4c59-b60b-4c9edd295053.png)
