### ISSUE TITLE
[W6-API-sentiment-project] Eduardo Rivera

### ISSUE THREAD

**Issue by Eduardo-Rivera98** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#19]
https://github.com/Eduardo-Rivera98/PROJECT-Flask_HIMYM.git

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Edu 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Vamos con el readme que ha quedado un poco cortito en este caso. Que es lo que me ha faltado: 

- La documentación de la API, tienes un fichero separado, lo cual esta guay, peeero me han faltado algunas cosinas: 

  - Ponme algun ejemplo de lo que nos devolverían cada uno de ellos. 

  - Puedes poner el link a esta documentación en el readme original. 

- Las librerías que has usado para el proyecto

- Este proyecto tiene una estructura de carpetas bastante más compleja, por lo que sería interesante incluir un apartado donde explicaramos que carpetas tenemos y que ficheros tenemos en cada carpeta.

- Pon el link de donde has escrapeado los datos. 

## Estructura del repo

Vamos con la organización que no esta muy fina en este caso: 

- Tienes unas cuantas carpetas temporales que deberían ir al`.gitignore` como por ejemplo el `__pycache__` o el `.ipynb_checkpoints`

- El `csv` que tienes, aunque sea solo uno, a una carpeta que se llame por ejemplo `data`

- Tienes una carpeta que se llama `notebooks_sucios`, si es algo para ti donde has ido haciendo pruebas, lo ideal es que no se vea, por lo que deberíamos meterlo en el `.gitignore`

- Todos los jupyters, que entiendo que son definitivos, que estan "sueltos" por el repo, metelos en una carpeta. Además, si nos numeras para saber el orden de trabajo sería suuper TOP. 

- Tienes fichero con código SQL. Aquí de nuevo, crea una carpeta que se llame `sql_scripts` y metelo en ella.
  
- El archivo `config.py` mételo en la carpeta de `src`. 

## Sintaxis de código

- A lo largo del repo tienes cosas en ingles y otras en español, cuidado con esos detalles. Intenta homogeneizarlo. 

- En el jupyter de limpieza, tienes funciones. Nos las deberíamos llevar a un `.py`. Recuerda, nos podemos crear todos los `.py` que queramos, donde cada uno de ellos tenga funciones con objetivos específicos. Es decir, te puedes crear un `.py` que se llama `scarp_functions` donde tengamos todas esas funciones. 

- En algunas funciones tienes *docstrings*  y en otras no. Intenta terminar las que no los tienen. Por otro lado, las que si tienen *docstrings* hay que intentar que estén bien definidos. 

  Recuerda, ¿qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Sobre la función `change`, esto es lo que tienes: 

  ```python
  def change(x):
    if x == 'Future Ted VO': #
        return 'Future Ted(Narrator)'
    elif x== 'Ted (2030)':
        return 'Future Ted(Narrator)'
    elif x== 'Ted (voix off)':
        return 'Future Ted(Narrator)'
    elif x== 'Ted from 2030':
        return 'Future Ted(Narrator)'
    elif x== 'NARRATOR':
        return 'Future Ted(Narrator)'
    elif x== 'Narrator':
        return 'Future Ted(Narrator)'
    elif x== 'BARNEY':
        return 'Barney'
    elif x== 'TED':
        return 'Ted'
    elif x== 'MARSHALL':
        return 'Marshall'
    elif x== 'ROBIN':
        return 'Robin'
    elif x== 'LILY':
        return 'Lily'
    elif x== 'Waitress':
        return 'Wendy'
    else:
        return x

  # 🔴 cuando vemos una función de este tipo y vemos tantos elif tenemos que pensar que hay que podemos hacer. Y la solución suele ser un diccionario. 

  # como lo podríamos hacer?

  def change(x):
    diccionario = {
      'Future Ted(Narrator)' : re.match('.*Future.*', x), 
      'Ted ': re.match('.*Ted.*', row), 
      ... # y así para todos los que quieras}
    for key, value in diccionario.items():
      if value:
        return key
      else: 
        return "No info"

  df4['personaje']= df4['personaje'].apply(change)

  # ⚠️ te escribí pseudocódigo. Por lo que puede que no funcione al 100%, pero por ahí van lso tiros.s
  ```
- Al final del jupyter de limpieza tienes algo con texblob. Dos cosinas sobre esto: 
  - Los imports siempre al inicio del jupyter

  - Si es solo una prueba, recuerda que debemos intentar dejar nuestro jupyter lo más limpio posible. 

- Lo mismo, en el jupyter de sql tienes todas las funciones metidas en el jupyter. Al `.py`! 

- El jupyter de `demo` lo tienes practicamente vacío. Para dejarlo así, mejor no incluirlo. 

## TODOs

Bueno Edu, en general el proyecto esta bien, aunque me ha parecido que estaba muy mal organizado y un poco caótico (tenemos cosas en ingles y otras es español, funciones dentro de jupyters, jupyters vacios, etc.) 

Te dejo por aquí un pequeño recap de las correcciones:

- Atomizar algunas funciones
- *docstrings*, *docstrings*, *docstrings* 😂
- Reorganizar un poquito el repo
- Algunos detalles del readme como las librerias que has usado o la estructura del repo

Venga venga venga que ya no queda nadaaaaaa 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/144841903-1a38b7ee-71cd-4b7e-90dc-3d56ab166c2b.png)
