### ISSUE TITLE
[api-sentiment-project] Andrés Pérez

### ISSUE THREAD

**Issue by Andrestart** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#2]
https://github.com/Andrestart/sentiment_analysis.git

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Andrés 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README
Me ha encantado tu readme 🔝! Te dejo por aquí un par de detallines:  

- Super bien que hayas separado el readme del proyecto de la documentación de la API 👏🏽. 

- Sobre la documentación de la API: 
  - Me ha faltado que pusieras algún ejemplo de lo que nos devuelve cada endpoint o por lo menos alguno. 

- Sobre el readme del proyecto: 
  - Lo único que me ha faltado es: este proyecto tiene una estructura de carpetas más compleja. Lo ideal para facilitar al lector el trabajo, es hacer un apartado donde incluyamos la estructura de las carpetas, explicando muy brevemente que nos podemos encontrar en cada una de ellas. 

Por el resto, trabajazo Andrés, muy buen readme 👏🏽!

## Estructura del repo

Suuper bien modularizado el repo Andrés! Solo un par de detalles: 

- Tienes una imagen por ahí suelta, nos podemos crear una carpeta de imagenes donde almacenemos, aunque sea solo una. 

- Tienes una carpeta que se llama `tables` donde guardas el `csv` y el código de `sql` que te genera tu BBDD. Mi recomendación: 

  - Crearnos una carpeta `data` donde tengamos los datos del csv

  - Crearnos una carpeta que se llame por ejemplo `sql_scripts` donde guardemos todo el código de `sql` , es decir, el código que genera la BBDD. 

Por el resto todo perfecto! 

## Sintaxis de código

- En la parte de la limpieza de los `csv` si te fijas repites el código tres veces, una para cada `csv`. Esto es viable en este caso porque solo tenemos 3 `csv`. Pero imaginate que tuvieramos 50, menudo coñazo! 

  Lo que podríamos hacer es crearnos una función que recibiera el dataframe sucio y nos lo devolviese limpio. 

  Para luego finalmente solo concatenar todos los ficheros limpios. 

- Sobre los *docstrings*  de tus funciones. Super bien que los hayas hecho. Solo como detalle: 

  ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```

Por el resto todo super bien Andrés! Has sacado un montón de enpoints para el análisis de sentimientos! Me gusta 😍. 

## TODOs

- Darle una vueltina a los *docstrings* de las funciones. 
- Contar un poco la estructura del repo en el readme
- Reorganizar un poco la carpeta de `tables`, pero solo un poquito. 
- Como reto para el futuro, meter más *enpoints* de post, como por ejemplo uno de actualizar o eliminar alguna frase. 


Bueno Andrés, super buen trabajo en este proyecto. Seguimos que ya no queda nadaaaa 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/144744844-3a0069e9-94ab-43ea-96cc-ad04566825af.png)
