### ISSUE TITLE
[W6-api-sentiment-project] Luis Serrano

### ISSUE THREAD

**Issue by LuisSerranoCerame** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#20]
https://github.com/LuisSerranoCerame/FrasesPK

**Comment by AnaAGG** [comment]
Hola hola Luis, 

Sabemos que un proyecto sin readme es un proyecto NO entregado. Además, has tenido una semana para trabajar en el readme y poder subirlo. 

He optado por no considerarte el proyecto como no enviado, pero no se te mandará feedback sobre tu trabajo.
