### ISSUE TITLE
[W6] Fernando Zapico, La vida es suAPI

### ISSUE THREAD

**Issue by 4tolon** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#21]
https://github.com/4tolon/la_vida_es_suAPI

![](https://i.pinimg.com/originals/2d/af/99/2daf991d9bd26c3b08ba24270dd5eca3.gif)

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Fernando 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Tienes un readme espectacular Fer! Super bien que hayas documentado la API en un fichero aparte, solo algunos detalles: 

- En el readme principal puedes: 
  - Poner el link de la página que escrapeas
  - Poner un link que te lleve al documento de la documentación de la API
- En el documento de la API, podrías haber incluido algún ejemplo de lo que nos devuelve la API en cada uno de sus endpoints.

Pero vamos, que son detallines, buen trabajoooo 💪

## Estructura del repo
En general esta todo super bien modularizado y bien explicado, pero ya sabes que siempre tenemos un comentario que hacer, te los dejo por aquí: 

- La carpeta de `sucio`, la tienes dentro de `notebook`. Ya que se trata de una carpeta "personal" donde has ido haciendo tus pruebas, y en realidad no le aporta valor al proyecto en si, lo ideal es meterlo dentro del `gitignore` para que la gente no la pueda ver. 

- Se nos han escapado fuera del `.gitignore` algunos archivos de esos rarinchis como el `__pycache__` dentro de `config` y `tools`. 

- Tienes este archivo `banner.py` dentro de la carpeta `data`, lo ideal que lo metas en la carpeta donde tienes todos los `.py`.

- Se te ha pasado una imagen fuera de la carpeta de `img`. 

- Te podrías haber creado una carpeta que se llamara por ejemplo `sql_scripts` donde incluyeras todos los scripts de sql, por ejemplo el script que te crea la base de datos. 

## Sintaxis de código

- Vamos con la parte de Selenium:
  - Lo primerito de todo, darte la enhorabuena por sacar tus datos usando Selenium. Un nuevo reto en este proyecto

  - Si no se me ha pasado nada, cuando haces el scrapeo de los tres actos lo hacer con el mismo código que repites tres veces. Pero si te fijas las url de los actos se diferencian en un número, por lo que podríamos hacerlo con un format y for loop para evitar repetir ese código. 

  - En este jupyter dejaste las funciones en el jupyter. Recuerda llevarlas a un `.py`. Lo bueno, las tienes todas documentadas! 

- Eso si, tienes funciones que no están documentadas. Revisalo y terminalos para que te quede todo perfectito. 
- Vamos con este jupyter 3_post_times: 
  - Entiendo que este es el jupyter para sacar los tiempos que no fuiste capaz. Genial que lo incluyas. Pero, por si sigues trabajando e ello, intenta documentarlo mucho para que sea más fácil de seguir! 
- Sobre el último jupyter, donde haces los ejemplos a las llamdas de tu API: 
  - Genial que lo incluyeras
  - Pero ten cuidado que tienes por ahí algun print infinito! 
  - Mueve las funciones que tienes al `.py` que tienes con las funciones del análisis de sentimientos, no las tienes todas metidas en ese fichero. 
  
## TODOs

Como ves, las cositas que te dije son detalles. En general tienes un trabajo ESPECTACULAR, enhorabuena Fer! Te dejo por aquí un *recap*  de las cosas que te fui diciendo: 

- Meter alguna carpetita más en el repo para los códigos de sql
- Rematar las funciones y sus *docstrings* 
- Como reto! Quitar todo ese html del main y llevarnoslo a otro fichero 
Venga Fer, que ya estamos en la recta final 💪🔥!!!!

![image](https://user-images.githubusercontent.com/75084991/145001566-dc1836f5-2d11-45ba-b819-66ce5865af21.png)
