### ISSUE TITLE
[W6-api-sentiment-project] - Nicolás

### ISSUE THREAD

**Issue by NicolasPce** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#22]
https://github.com/NicolasPce/P4

**Comment by AnaAGG** [comment]
Hola hola Nico! 

Bueno, tu readme en realidad no es un readme y todos sabemos lo que pasa cuando entregamos un proyecto sin readme... Lo consideramos como no entregado. En este caso, seré un poco benévola y no lo consideraré no entregado, pero no te daré feedback. 

Aún así, lo que he visto, lo he visto bastante incompleto. Queda mucho por trabajo por hacer ahí 😔
