### ISSUE TITLE
[W6-api-sentiment-project] DaniHelguera

### ISSUE THREAD

**Issue by Danihelguera** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#23]
https://github.com/Danihelguera/W6-api-sentiment-project_DaniHelguera-.git

**Comment by AnaAGG** [comment]
# Proyecto Flask

Hola hola Dani 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README
Menudo readme más completo Dani, enorme trabajo 👏🏽! Vamos con algunos detalles de cara al futuro por si te aporta valor:

- Tienes las librerías y los links a la documentación oficial 👏🏽! Pero no se nos ven bien en el markdown 😔. Creo que con que le quites la tabulación se verá perfecto. 

- Me han faltado la documetación de la API, esencial para saber como funciona. Si además le incluimos algunos ejemplos sería perfecto. 

- Haces una descripción super detallada de todos tus procesos. Como recomendarción dos detallines:  
  - Lo tienes todo en un único bloque de texto. Intenta, para facilitar la lectura ponerlo en modo de lista
  - Hay cosas que podríamos evitar como por ejemplo: 
    - Cuando cuentas el número de valores nulos que tienes por columnas
    - Cuando explicas todas las funciones que tienes y lo que hacen

Los readmes tienes que ser algo esquemático y que podamos ver de una forma rápida. Pero bueno Dani, son detalles 😉.

## Estructura del repo
En general esta bien Dani, pero te dejo por aquí unos *tips* de cara al futuro: 

- En la carpeta de `data` tienes todo el código para crear tu BBDD. Esto es un poco autointuitivo. Como recomendación lo pondría en una carpeta aparte que puedas llamar `SQL_scripts` o `Scripts_createBBDD` o algo similar. Algo que nos diga desde el principio que ahí tenemos el código que crea nuestras tablas. 

- En la carpeta `Notebooks_and_Skripts` se nos ha colado la carpeta de checkpoints del jupyter. Recuerda que este tipo de carpetas o ficheros que se nos crear deben ir al `.gitignore` ya que es información que no es útil para el proyecto. 

- El `main.py` por convención debe ir en la raíz del repo. 

- Esta carpeta Notebooks_and_Skripts` me ha parecido un poco cajón de sastre. Vamos a ver como lo podríamos reorganizarlo para entenderlo mejor: 
    - Sacaría la carpeta `config`fuera a la raíz del repo, donde tendría el `__init__.py` y el `config.py`
    - Me crearía una carpeta que se llamara `src` donde tuviera el `sql_tools` y todos los ficheros que necesitara para almancenar mis funciones
    - Me crearía una única carpeta de para notebooks. Hay guardaría unicamente jupyters. 
    - Los scripts de sql a una única carpeta, los podríamos juntar con los scripts que nos generan las BBDD. 
    - Lo mismo para las imagenes, aunque sea 1. Nos creamos una carpeta y las guardamos ahí. 
- Tienes algunas cosas en ingles y otras en español. Intenta homogeneizarlo todo al mismo idioma. 


## Sintaxis de código

- En este jupyter `03_Feeding_the_SQL_DataBase`  tienes un *for* para ir chequeando el avance. Solo por si te aporta valor, en python tenemos la librería `tqtm` que nos permite hacer justo esto. Te dejo por [aquí](https://tqdm.github.io/) algo de documentación por si te interesa.

- Sobre los *docstrings*, los tienes en todas las funciones, pero me faltan algunas cositas. 

    ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función MUY SINTETIZADO, EN UNA ÚNICA LÍNEA
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Daniiiiiii los *prints* infinitos, estoy llorando por dentro 😭!
- En el jupyter de `05_Sentiment_analysis` tienes las funciones. Lo ideal, que nos las llevaramos a un `.py` nuevo que almacenaramos en el `src`. Recuerda que nos podemos crear tantos `.py` que nos queramos con objetivos específicos. Y documenta esas funciones. 
- El análisis de sentimientos suuper top Dani. Siguiente reto, meterlo como *endpoint*  en la API. Si quieres que lo veamos un día me dices 😉! 


## TODOs

Bueno Dani, super proyectazo. Has hecho un gran trabajo, casi todo lo que te dije son m´sa detallines que otra cosa. Te dejo por aquí un resumen de las cosinas que te dije: 

- Organizar un poco mejor el repo
- El readme, intentar sintetizar un poco más y meter la documentación de la API. 
- Darle una vueltita a los *docstrings* 

Venga Dani que ya estamos en la recta final 🔥🔥🔥!!!!

PD: Una de las cosas que más me gustaron de tu proyecto es que a pesar de usar algunas funciones de Ras has creado mucho código nuevo. Enhorabuena! 

![image](https://user-images.githubusercontent.com/75084991/144708803-2f645478-7784-4b57-9835-95e36e043988.png)
