### ISSUE TITLE
[W6-api-sentiment-project] Pedro Martínez

### ISSUE THREAD

**Issue by pedromartinezleis** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#24]
https://github.com/pedromartinezleis/api-sentiment-project

Está pendiente de acabar el endpoint

**Comment by AnaAGG** [comment]
# Proyecto Flask

Hola hola María 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

Vale Pedro, si que es cierto que el proyecto está incompleto. Pero dada la situación no me voy a poner exigente. 

Lo que si te pediría es que intentes terminarlo de alguna forma, estoy segura que lo harás sin problema!
