### ISSUE TITLE
[api-sentiment-project]Alvaro Fidalgo

### ISSUE THREAD

**Issue by Afidalgo-fmm** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#3]
https://github.com/Afidalgo-fmm/Proyecto-4.git

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Álvaro 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README
Vamos con el readme, que te diré que vamos a aceptar pulpo como animal de compañia... 

¿Qué es lo que teníamos que haber puesto en el readme?

- El objetivo, que en el caso de este proyecto era hacer una API usando Flask y SQL.

- Qué herramientas has usado para llevar a cabo el proyecto. 

- Cual es la estructura del repo, en este proyecto deberíamos tener muchas carpetas con muchos archivos, lo que lo hacía difícil de seguir. 

- Las librerías que hemos usado y los links a la documentación oficial. 

    ¿Cómo hacemos esto? 

     ```
    [pandas](https://pandas.pydata.org/)
    ```
- De donde sacas los datos de Rick y Morty. Pon el link para que la gente pueda acceder a los datos. 

- El objetivo era hacer una API, y había que hacer la documentación de la API. 
  - Qué *endpoints*  de GET tienes
  - Qué *endpoints* de POST tienes
  - Ejemplos de tus *endpoints* 


## Estructura del repo

Vamos con al estructura, que después del readme es lo que un *recruiter* verá de nuestro trabajo. 

- Tienes una carpeta de datos, lo cual esta perfecto 👏🏽

- Tienes varios jupyters que están "sueltos" por el repo. Lo ideal, agruparlos en una única carpeta que se llame por ejemplo `Notebooks`. Si encima los numeramos para saber el orden de trabajo quedaría suuper bien. 

- Tenemos que evitar dejar ficheros con nombres ambiguos, como es el caso de estos nombres `Untitled.ipynb`. 

- Se nos han pasado algunos archivos temporales, como el `__pychache__` fuera del `.gitignore`. Recuerda que este tipo de archivos no queremos que se vean en nuestros repos y por lo tanto debemos incluirlos en el `.gitignore`. Lo mismo te diría del jupyter que tienes que se llama `prueba`, supongo que ahí harías tus pruebas para ver si funcionaba. Como es algo personal que no aporta valor al proyecto, al `.gitignore`. 

- La carpeta `s`, recuerda que por convenio se debe de llamar `src`. Pero super bien que la tengas creada 👏🏽! 

## Sintaxis de código

Sobre esto lo primerito de todo como comentario general. En este proyecto era **OBLIGATORIO** trabajar con SQL, sé que tienes problemas , pero deberíamos haber buscado una solución para esto. 

- A ver... Es que solo me puedo reir. Cuando hacemos el `getpass` el objetivo es que no se muestre la contraseña en el jupyter. Peeeero como mensaje tu pones la contraseña! 

    ```python
    dbName = "RickandMorty"
    contra = getpass("escribe admin") # LE ESTAS DANDO LA CONTRASEÑAAAAAAA, por lo tanto ya no tiene sentido que usemos el getpass 😂
    ```
- Me ha faltado un jupyter donde hagas algunos ejemplos de tu API. Principalmente para los POST. 

- Independientemente de que lo hicieras en mongo o SQL: 
  - Solo tienes tres endpoints. 
  - No has hecho el análisis de sentimientos , lo cual dices que es el objetivo de tu proyecto, 
  - Tienes las funciones sin documentar. 

    ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```

Lo siento Álvaro, pero no es un trabajo de semana 6-7 de bootcamp. Queda mucho trabajo por hacer, y no puedo darte otro feedback más que este. No dudo que no hayas trabajado, pero debemos darle una vueltina a este proyecto. 

![image](https://user-images.githubusercontent.com/75084991/144706502-8a19aaa7-4a40-470f-ad30-2fecdd783a41.png)
