### ISSUE TITLE
[Api Sentiment Project] LYDIA

### ISSUE THREAD

**Issue by Lydia-Arocena** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#4]
https://github.com/Lydia-Arocena/PROYECTO4_SENTIMENTS

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Lydia 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Tienes una gran documentación de tu API, pero me han faltado la parte que explicas de que va el proyecto y que es lo que nos vamos a encontrar, que podíamos incluir? 

  - Las librerías que hemos usado y sus link.

  - Este proyecto tenía una estructura de carpetas algo más compleja. Podríamos haber incluido un apartado donde contáramos que carpetas teníamos y que nos podíamos encontrar en ellas.

  - Podíamos también incluir de donde has sacado el dataset y poner el link de la página donde lo has descargado. 

  - Por último, el *workflow* del proyecto. Es decir, que pasos seguiste para conseguir tus objetivos. 

## Estructura del repo

En general el proyecto esta super bien modularizado, buen trabajo Lydia. Aún así te dejo por aquí unos comentarios para dejarlo redondito del todo: 

- Se nos han pasado algunas carpetas de archivos temporales, como los checkpoints y el `__pycache__` fuera del `.gitignore`

- Suuper bien que hayas incluido una carpeta de mysql con todos los archivos de la base de datos 👏🏽! 

- En la carpeta de `notebooks` recuerda, si los numeramos para saber cual es el orden de trabajo siempre ayuda. 

- Te has dejado el `.env` fuera del gitignore con la contraseña de mysql 😱!!!!

- Tienes una imagen por ahí suelta. Lo ideal, crearnos una carpeta de imagenes y guardarla allí, aunque sea solo una. 

## Sintaxis de código

Vamos con el codiguinchi! 

- Lo primerito de todo, tienes unas cosas en ingles y otras en español. Intenta homogeneizarlo todo. 

- Super bien que hayas añadido los *docstrings*, pero recuerda que como todo tenemos un convenio para escribirlos. 


   ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```

- Nos queda terminar de mirar lo de las funciones de `replace_author_id` y `replace_genre_id`!!!!!

- Super bien que incluyeras un jupyter con ejemplos de los endpoints de tu API. 

- En el método post, lo tienes creado para que el usuario meta una nueva frase, pero tiene que meter el id del autor. Que follón! En este caso: 
  - O das una guía muy clara de sus autores e id, lo cual puede ser un poco doloroso
  - O que hagan el post poniendo el nombre del autor, y que por detrás pasen cosas para sacar su Id. Es más, esa función ya la tienes. 

Por el resto todo perfecto Lydia, este repo no tenía gran parte de código una vez pasado el  momento de meter los datos en sql. 

## TODOs

Como resumen de lo que te puesto por aquí: 

- El `.env` al `.gitignore` 🚨
- Los *docstrings* en las funciones, formatealos para tenerlos con la estructura correcta. 
- En el readme poner la parte de explicación del proyecto. 

Venga que ya estamos en la recta final 💪🔥🔥! 


![image](https://user-images.githubusercontent.com/75084991/145149787-01cf42b6-81e9-4f54-b511-2238be622398.png)
