### ISSUE TITLE
[W6-api-sentiment-project]BeaSánchez

### ISSUE THREAD

**Issue by Beapsp** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#5]
https://github.com/Beapsp/Proyecto_crear_API

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Bea 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Bueno Bea, tienes un readme suuper completo, enhorabuena 🙌🏽. Pero ya sabes que siempre te dejo un par de detalles: 

- Me han faltado las librerías que has usado en el proyecto. 

- Nos cuentas todos los endpoints que tienes, tanto los de GET como lo de POST. L o que podríamos haber includido es algun ejemplo de lo que nos devuelve cada endpoint. 

- Podrías también haber contado de donde has sacado los datos y poner el link a la página. 

- Este proyecto tenía una estructura de carpetas bastante más compleja que otros proyectos. Lo que podíamos hacer es añadir esa parte en el repo, donde muy esquemáticamente expliquemos que carpetas y ficheros tenemos. 

Por el resto todo bien Bea! 

## Estructura del repo

Super bien organizado Bea!!! 

- Se nos han pasado algunos ficheros importantes fuera del `.gitignore` como por ejemplo:
  - Los checkpoints del jupyter
  - `__pycache__` en la carpeta de `config` y el `src`

- 🚨 El `.env` cuidado que lo has dejado también fuera del `.gitignore`. 🚨

- En la carpeta de `notebooks` tenemos dos, lo que podríamos hacer es numeralos para saber el orden de trabajo. 

- Por último, en este proyecto yo crearía dos carpetas nuevas: 
  - Una con las imagenes
  - Una con todos los ficheros de sql, que la podemos llamar `sql_scripts`

- Super bien que tengas un jupyter con ejemplos de tus endpoints, de como funcionan y que nos devuelven. 

Por el resto todo perfectito 😉

## Sintaxis de código

- Cuidado con los *docstrings* Bea. Los tienes, lo cual está perfecto, pero cuidado, no los tenemos del todo bien organizados: 

  ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
- Solo como detalle por si te aporta valor, cuando haces el `apply` a las tres columnas lo haces por separado. 

  Esto también lo podemos hacer todo en una única línea de código: 


  ```python
  df_movies[["Catchphrase", "Movie_Name", "Context"]] = df_movies[["Catchphrase", "Movie_Name", "Context"]].apply(cl.sustituye)
  ```
- Se te han quedado algunas funciones en el jupyter (`replace_movie_id`) en el jupyeter donde insertas los datos a SQL. 

- 🟠 No sé si al final os llegó a funcionar lo que estuvimos viendo del apply con la lista. Dime, para que no quede eso pendiente. 

- En el `.py` de `sql_tools` te han faltado todos los *docstrings* de las funciones. 

Por el resto de código no puedo decirte mucho, la mayoría de las funciones vienen derivadas de la clase. 

## TODOs

Como siempre te dejo por aquí un *recap* de la corrección:

- Los *docstrings* de las funciones:

  - Hacerlos en las que no tienen

  - Rematarlos en las que si los tienes

- La contraseña de sql que esta a la vista! 

- Incluir las librerías que has usado en el proyecto y de donde has sacado los datos. 

- EL `.gitignore`

- Incluir alguna carpetilla más en el proyecto, para el código de sql y las imagenes. 


Bueno Bea, muy muy buen trabajo de verdad! Increíble tu evolución de las últimas semanas 🔝. 

Venga que ya no queda nadaaa 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/144827215-a96dd393-a5f8-4506-8ad1-70f38c4368a2.png)
