### ISSUE TITLE
[W6-api-sentiment-project] Alfonso Romero

### ISSUE THREAD

**Issue by aromegar** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#7]
https://github.com/aromegar/Simpsonent_Analysis.git

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Hola hola Alfonso 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README
Un readme claro y conciso, buen trabajo Alfonso. Pero como siempre, aquí van unos detallines por si te aportan valor: 

- Te bajas los datos de kaggle, lo ideal es que hubieras puesto el link a la página. 

- Sobre la documentación, bien que hayas puesto el los enpoints que tienes y lo que nos devuelve cada uno. Me ha faltado algún ejemplo. Quiero decir, Este endpoint, se llama de esta forma, hace esto y aquí un ejemplo de como lo llamamos y que nos devuelve. 

- En la parte de los *imports* me han faltado algunas librerías, como por ejemplo sqlalchemy.
  
## Estructura del repo
Tienes un repo pequeñito, por lo que la organización no era demasiado compleja. Aún así has consguido modularizarlo todo bastante bien Alfonso 👏🏽. Te dejo por aquí unos *tips* 

- Tienes un jupyter, lo ideal, aunque sea solo uno, crearnos la carpeta de notebooks y meterlo ahí. 

- No veo el `.gitignore`😔, lo que quiere decir que los archivos temporales que se nos crean los has quitado a mano. A ver, esto esta bien, pero no es lo correcto. Recuerda que siempre tenemos que tener nuestro `.gitignore`

- Me ha faltado el archivo de configuración, que será donde hagamos nuestra conexión con la BBDD de sql. 

  ```python
  # ese archivo debe contener: 
  import sqlalchemy as alch
  import os
  import dotenv

  dotenv.load_dotenv()

  passw = os.getenv("pass_sql")
  dbName = "NOMBRE DE TU BBDD"
  connectionData = f"mysql+pymysql://root:{passw}@localhost/{dbName}"
  engine = alch.create_engine(connectionData)
  ```

- En este proyecto también teníamos que crearnos una BBDD, lo cual nos genera un esquema y un código (el que genera nuestra BBDD), lo ideal que guardemos ese código para poder replicar esa BBDD en otro momento. Todas esas consinchis las podemos guardar en una carpeta que se llame `sql_scripts` o algo similar. 
  
- En este proyecto también podíamos incluir un jupyter donde hicieramos llamadas a nuestra API para que pudieramos ver si funcionaban. 

- Los *docstrings` en las funciones! 

## Sintaxis de código

Vamos con el código. La verdad es que este proyecto no ha sido tu mejor obra Alfonso. 

EL código que tienes este bien, pero lo veo un poco incompleto. Vamos con algunos detalles sobre esto:

- Faltan endpoints de post, como insertar, eliminar o acutualizar.

- Creas una query para sacar un dataframe para hacer el análisis de sentimientos pero no lo haces 😔

- Para lo ordenado que eres tu, el jupyter está bastante caótico, ¿qué pasó con este proyecto? Fue cuando se te inundó la casa? 

Aún con todo veo cosas muy interesantes ed código, con queries de SQL usando joins, etc.

## TODOs
Bueno Alfonso, la verdad es que tengo poco que decirte respecto a tu trabajo en este proyecto. Te dejo por aquí unos *tips* 

- Los *docstrings* en las funciones. 
- Archivo de configuración de la API
- Incluir más *enpoints* 

Aún así, si necesitas que veamos algo en concreto o charlar dime y lo vemos juntos 😉

![image](https://user-images.githubusercontent.com/75084991/144742750-c2ad361d-6ae9-44ac-a537-6f8fa8e65935.png)
