### ISSUE TITLE
[ W6-api-sentiment-project] Ester Fernández

### ISSUE THREAD

**Issue by emarfer** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#8]
https://github.com/data2021oct/W6-api-sentiment-project

**Comment by AnaAGG** [comment]
# Proyecto Flask

Hola hola Ester 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Increible Ester! Aunque no te lo creas no tengo nada que decirte, has hecho un trabajo perfecto! 

## Estructura del repo

En general el repo esta muy bien modularizado, con distintas carpetas y con casi todo los ficheros rarinchis en el `.gitignore`. Aún así, te dejo por aquí algunos detallines: 

- Se nos han colado algunos archivos temporales fuera del `.gitignore`, vamos la pelea de siempre! ¿Qué archivos son? 

  `__pycache__` dentro de la carpeta `config`

- Como en este proyecto tenemos mucho código de sql, lo que podríamos haber hecho es añadir una carpeta que se llamara `sql_scripts` donde  incluyeramos todos esos ficheros. 

- Tenemos dos veces el `__init__.py` en el repo, lo ideal dejarlo junto con las `sql_tools`

Por el resto todo perfectito Ester! 

## Sintaxis de código

- Respecto a este código: 

  ```python
  friends["episode_number"] = friends.episode_number.astype('int64')
  friends["season"] = friends.season.astype('int64')

  # solo como detalle, lo podemos hacer en una única líena
  friends[["episode_number", "season"]] = friends.episode_number.astype('int64')
  ```
- Cuando haces la limpieza de los nombres de los personajes, tienes este código: 

  ```python
  friends.character = friends.character.str.replace("Mnca","Monica")
  friends.character = friends.character.str.replace(r"(Rach.?$)","Rachel",regex = True)
  # y así para todos los personajes. Pero si te fijas, repites el código muchas veces. La solución, un diccionario y una función ! 

  # te dejo por aquí algo de pseuso-código por si te ayuda a tirar: 
  def change_character(x):
    diccionario = {
      'Rachel' : re.match('.*Rach|rach.*', x), 
      'Monica ': re.match('.*Mon|mon.*', row), 
      ... # y así para todos los que quieras}
    for key, value in diccionario.items():
      if value:
        return key
      else: 
        return "error

  friends.character = friends.character .apply(hange_character)
  ```
- Tienes algunas cosas en ingles y otras en español, por el ejemplo el readme en ingles y los *docstrings* de las funciones en español. 

Por el resto todo perfectito Ester! 

## TODOs

Bueno Ester, la verdad es que tengo poco que decirte, has hecho un trabajo excelente! 

- Atomizar algunas funciones 
- Meter en el `.gitignore` algunos de los archivos rarinchis que se nos han colado. 
- **COMO RETO**: te has creado las funcioncitas para el análisis de sentimientos y encima te has sacado gráficas. Lo siguiente, meterlo como un endpoint de nuestra API. 

Venga venga venga Ester que esto esta casi hechoooo 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/144847610-295e882e-4762-46b9-8f01-b2396878f20b.png)
