### ISSUE TITLE
[W6-api-sentiment-project] - Guillermo Perinat

### ISSUE THREAD

**Issue by Pnat1** [Ironhack-Data-Madrid-Octubre-2021/W6-api-sentiment-project#9]
https://github.com/Pnat1/W6-api-sentiment-project.git

**Comment by AnaAGG** [comment]
# Proyecto Flask

Hola hola Guille 🙋🏻‍♀️! Y por aquí de nuevo con más comentarios🤓! 

## README

Guileeeeee que el readme de tu proyecto es el readme que os presentamos nosotras!!! Venga, vamos a aceptar pulplo como animal de compañia.. 

- ¿Qué es lo que teniamos que tener en este readme? 

  - Objetivo del proyecto

  - Herramientas que hemos usado

  - Ejemplos de tus endpoints

  - Contar de donde habías sacados los datos y que es lo que nos contaba

  - Poner las librerías que hemos usado y los links a la documentación

  - Incluir un apartado donde contemos la estructura del repo

## Estructura del repo

Sobre esta parte Guille, ha habido una gran mejoría de proyectos anteriores a este, enhorabuena! Aún así, te dejo por aquí algunos detallines más por si te aportan valor: 

- La carpeta de los checkpoints de los jupyters, recuerda que esto no es importante para nuestro repo y que por lo tanto debe ir al `gitignore`. 

- En la carpeta de notebooks tienes un poco de jaleito. Vamos por partes:
  - Tienes un archivo `sql` con el código que crea tu BBDD. Lo ideal sería que te crearas una carpeta nueva donde almacenaramos todos los códigos de sql que podamos tener.
   
  - Tienes un fichero que se llama configuration. Esto debería ser una carpeta que tuvieramos fuera de `notebooks` y que contuviera  los ficheros de configuración con el código que tienes tu en ese fichero.

  - Puedes numerar los ficheros para saber el orden de trabajo.

- Este fichero `api_flask_main` no tiene extensión, recuerda que tiene que ser un `.py`.   

## Sintaxis de código

- Cuando haces esto: 

  ```python
  df_script = pd.read_csv('../data/pulp_fiction_clean')
  df_script = df_script.drop(["Unnamed: 0"], axis= 1)

  # en python tenemos un parámetro dentro del método `read_csv` que nos permite especificar que no nos muestre la columna Unnamed:0, es el `index_col`= 0
  df_script = pd.read_csv('../data/pulp_fiction_clean', index_col = 0)
  ```
- Te han quedado algunas funciones en los jupyter. Recuerda llevarlas al `.py`

- Además, las funciones no tienen *docstrings*, esta parte, aunque puede resultar un coñazo es esencial para saber que hace tu función y que parámetros recibe. 

  ¿Qué es lo que tiene que tener un docstring? 
      - Qué es lo que hace la función
      - Qué argumentos recibe
      - Qué es lo que devuelve

      [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

      ```python
        def mifuncion(argumento1, argumento2):
          '''
          Lo que hace la función
          args: 
              argumento1: tipo de dato
              argumento2: tipo de dato
          return:
              que nos devuelve la función
          '''
          return "Hola"
      ```
- Ojo con los prints infinitos!!! Estoy llorando por dentro 😂

- Tienes algunos endpoints, unos de GET y otros de POST lo cual esta bien. A modo de reto para el futuro:
  - Añadir más endpoints de post, como unno de actualizar o eliminar una entrada de tu API
  - Crear más endpoints de POST con el análisis de sentimientos donde comparemos entre personajes o saquemos gráficas. 

## TODOs

En general estaba todo bastante completo. Te dejo por aquí un recap de las cosinas que te fui diciendo: 

- EL READMEEEEEE
- Los *docstrings* en las funciones
- Ordenar algo más el repo


Venga venga Guille que no queda nadaaa 🔥💪🔥 

![image](https://user-images.githubusercontent.com/75084991/145019365-75593d86-9508-4e50-a309-049f6d93ffa2.png)
